<?php

class HelperController {

    public $token;

    public function __construct($pToken) {
        $this->token = $pToken;
    }

    function get_contact_person_field()
    {
        // Lista de propiedades
        $properties_arr = [
            "profesion",
            "estado_civil",
            "n__cargas",
            "vivienda",
            "parroquia",
            "sector",
            "conyugue_c_i_",
            "conyugue_f__nacimiento",
            "conyugue_estado_civil",
            "conyugue_n__cargas",
            "conyugue_vivienda",
            "conyugue_provincia",
            "conyugue_ciudad",
            "conyugue_parroquia",
            "conyugue_sector",
            "conyugue_direccion",
            "conyugue_telf__movil",
            "actividades_principales",
            "sueldo___ingresos",
            "sueldo___ingresos_conyuge",
            "total_ingresos",
            "egresos_familiares_mensuales",
            "total_egresos",
            "total_ingresos_egresos_",
            "entidad_cuenta_bancaria_1",
            "entidad_cuenta_bancaria_2",
            "entidad_cuenta_bancaria_3",
            "numero_de_cuenta_bancaria_1",
            "numero_de_cuenta_bancaria_2",
            "numero_de_cuenta_bancaria_3",
            "tipo_cuenta_bancaria_1",
            "tipo_cuenta_bancaria_2",
            "tipo_cuenta_bancaria_3",
            "saldos_promedios_cuenta_bancaria_1",
            "saldos_promedios_cuenta_bancaria_2",
            "saldos_promedios_cuenta_bancaria_3",
            "protestos_cuenta_bancaria_1",
            "protestos_cuenta_bancaria_2",
            "protestos_cuenta_bancaria_3",
            "nombres_y_apellidos_referencia_familiar_1",
            "nombres_y_apellidos_referencia_familiar_2",
            "telf__fijo_referencia_familiar_1",
            "telf__fijo_referencia_familiar_2",
            "telf__movil_referencia_familiar_1",
            "telf__movil_referencia_familiar_2",
            "direccion_completa_referencia_familiar_1",
            "direccion_completa_referencia_familiar_2",
            "total_activo",
            "total_pasivos",
            "total_activo_pasivo_",
            "firstname",
            "lastname",
            "identificacion",
            "date_of_birth",
            "provincia",
            "ciudad_contacto",
            "address",
            "mobilephone",
            "phone",
            "activo_propiedad_1",
            "activo_direccion_1",
            "activo_valor_1",
            "activo_propiedad_2",
            "activo_direccion_2",
            "activo_valor_2",
            "activo_propiedad_3",
            "activo_direccion_3",
            "activo_valor_3",
            "activo_vehiculo_1",
            "activo_modelo_1",
            "activo_vehiculo_valor_1",
            "activo_vehiculo_2",
            "activo_modelo_2",
            "activo_vehiculo_valor_2",
            "activo_vehiculo_3",
            "activo_modelo_3",
            "activo_vehiculo_valor_3",
            "activo_vehiculo_4",
            "activo_modelo_4",
            "activo_vehiculo_valor_4",
            "pasivos_descripcion",
            "pasivo_institucion_1",
            "pasivo_valor_1",
            "pasivo_institucion_2",
            "pasivo_valor_2",
            "pasivo_institucion_3",
            "pasivo_valor_3",
            "pasivo_institucion_4",
            "pasivo_valor_4",
            "pasivo_institucion_5",
            "pasivo_valor_5",
            "edad",
            "edad_conyugue",
            "nombre_conyugue",
            "empresa_referencia_comercial_1",
            "empresa_referencia_comercial_2",
            "empresa_referencia_comercial_3",
            "fecha_inicio_referencia_comercial_1",
            "fecha_inicio_referencia_comercial_2",
            "fecha_inicio_referencia_comercial_3",
            "tipo_de_producto_referencia_comercial_1",
            "tipo_de_producto_referencia_comercial_2",
            "tipo_de_producto_referencia_comercial_3",
            "compras_mensuales_referencia_comercial_1",
            "compras_mensuales_referencia_comercial_2",
            "compras_mensuales_referencia_comercial_3",
            "plazo_referencia_comercial_1",
            "plazo_referencia_comercial_2",
            "plazo_referencia_comercial_3",
            "persona_que_confirma_referencia_comercial_1",
            "persona_que_confirma_referencia_comercial_2",
            "persona_que_confirma_referencia_comercial_3",
            "telefonos_referencia_comercial_1",
            "telefonos_referencia_comercial_2",
            "telefonos_referencia_comercial_3",
        ];

        return $properties_arr;
    }

    function get_deal_person_field()
    {
        // Lista de propiedades
        $properties_arr = [
            "hubspot_owner_id",
            "marca",
            "modelo",
            "amount",
            "cuota_inicial",
            "plazo",
            "asesor",
            "seguro",
            "cuota_mensual",
            "tasa",
            "tipo_de_credito",
            "compania",
            "meses_de_gracia"
        ];
        
        return $properties_arr;
    }

    function get_company_properties():array {
        return [
            "fecha_de_constitucion",
            "email",
            "contacto_principal",
            "cargo_del_contacto_principal",
            "apellidos_y_nombres_representante_legal",
            "cedula_de_ciudadania",
            "nacionalidad_representante_legal",
            "email_representante_legal",
            "telef__fijo_representante_legal",
            "telef__movil_representante_legal",
            "estado_civil_representante_legal__cloned_",
            "institucion_financiera_referencia_bancaria_1",
            "institucion_financiera_referencia_bancaria_2",
            "institucion_financiera_referencia_bancaria_3",
            "numero_de_cuenta_referencia_bancaria_1",
            "numero_de_cuenta_referencia_bancaria_2",
            "numero_de_cuenta_referencia_bancaria_3",
            "tipo_de_cuenta_referencia_bancaria_1",
            "tipo_de_cuenta_referencia_bancaria_2",
            "tipo_de_cuenta_referencia_bancaria_3",
            "antiguedad_referencia_bancaria_1",
            "antiguedad_referencia_bancaria_2",
            "antiguedad_referencia_bancaria_3",
            "cifras_promedio_referencia_bancaria_1",
            "cifras_promedio_referencia_bancaria_2",
            "cifras_promedio_referencia_bancaria_3",
            "credito_referencia_bancaria_1",
            "credito_referencia_bancaria_2",
            "credito_referencia_bancaria_3",
            "protestos_referencia_bancaria_1",
            "protestos_referencia_bancaria_2",
            "protestos_referencia_bancaria_3",
            "nombre_o_razon_comercial_proveedor_1",
            "nombre_o_razon_comercial_proveedor_2",
            "nombre_o_razon_comercial_proveedor_3",
            "insumo___producto_proveedor_1",
            "insumo___producto_proveedor_2",
            "insumo___producto_proveedor_3",
            "compras_mensuales_proveedor_1",
            "compras_mensuales_proveedor_2",
            "compras_mensuales_proveedor_3",
            "plazo_proveedor_1",
            "plazo_proveedor_2",
            "plazo_proveedor_3",
            "forma_de_pago_proveedor_1",
            "forma_de_pago_proveedor_2",
            "forma_de_pago_proveedor_3",
            "cargo_de_contacto_proveedor_1",
            "cargo_de_contacto_proveedor_2",
            "cargo_de_contacto_proveedor_3",
            "tel__contacto_proveedor_1",
            "tel__contacto_proveedor_2",
            "tel__contacto_proveedor_3",
            "periodo_fiscal_1",
            "periodo_fiscal_2",
            "activos_periodo_1",
            "activos_periodo_2",
            "pasivos_periodo_1",
            "pasivos_periodo_2",
            "patrimonio_periodo_1__cloned_",
            "patrimonio_periodo_2__cloned_",
            "ingresos_periodo_1",
            "ingresos_periodo_2",
            "costos_y_gastos_periodo_1",
            "costos_y_gastos_periodo_2",
            "utilidad_periodo_1__cloned_",
            "utilidad_periodo_2__cloned_",
            "suc__de_la_garantia",
            "id_garantia",
            "desc__garantia",
            "valor_de_la_garantia",
            "fecha_de_inicio_garantia",
            "fecha_de_finalizacion_garantia",
            "croquis",
            "name",
            "ruc",
            "address",
            "city",
            "state",
            "country",
            "phone",
            "periodo_fiscal_1_estados",
            "periodo_fiscal_2_estados",
            "periodo_fiscal_1_garantias",
            "periodo_fiscal_2_garantias",
            "actividad_es__principal_es____objeto_social",
        ];
    }    

    function get_deal_props_pj():array {
        return [
            "compania",
            "agencia",
            "fecha_de_solicitud",
            "solicitud_de_credito",
            "hubspot_owner_id",
            "codigo_del_producto",
            "hs_priority",
            "marca",
            "modelo",
            "cuota_inicial",
            "monto_a_financiar",
            "tasa",
            "periodos_de_gracia",
            "cuota_mensual",
            "cupo_solicitado"
        ];
    }

}
